--DECLARE @NUMNOTAS INT

--SET @NUMNOTAS = (SELECT COUNT(*) FROM [dbo].[NOTAS FISCAIS])
--SELECT @NUMNOTAS = COUNT(*) FROM [dbo].[NOTAS FISCAIS]

--PRINT @NUMNOTAS

IF (SELECT COUNT(*) FROM [dbo].[NOTAS FISCAIS]) > 70
	PRINT 'MUITA NOTA'
ELSE
	PRINT 'POUCA NOTA'