DECLARE 
@DATA_INICIAL DATE, 
@DATA_FINAL DATE,
@DATA_ATUAL DATE, 
@NUM_NOTAS INT = 0

--SET @DATA_INICIAL = '20170101'
SET @DATA_ATUAL = '2017-01-01'
SET @DATA_FINAL = '2017-01-10'

WHILE @DATA_ATUAL <= '2017-01-10'
--WHILE (SELECT DATA FROM [NOTAS FISCAIS] WHERE ) <= @DATA_FINAL
BEGIN
	SET @NUM_NOTAS = @NUM_NOTAS + (SELECT COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATA_ATUAL)
	SET @DATA_ATUAL = DATEADD(DAY, 1, @DATA_ATUAL)
END

--PRINT @DATA_INICIAL
PRINT @DATA_FINAL
PRINT @DATA_ATUAL
PRINT @NUM_NOTAS


-----------------------------------------------------------
--OU:



DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    PRINT CONVERT(VARCHAR(10), @DATAINICIAL) + ' --> ' 
        + CONVERT(VARCHAR(10), @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END