DECLARE 
@CLIENTE VARCHAR(10) = 'JOAO',
@IDADE INT = 10,
@DATANASCIMENTO DATE = '20201109',
@CUSTO FLOAT = 10.23,
@NUMNOTAS INT

SET @CLIENTE = 'JOÃO BB'
SET @IDADE = 11

PRINT @CLIENTE
PRINT @IDADE
PRINT @DATANASCIMENTO
PRINT @CUSTO
--@IDADE @DATANASCIMENTO @CUSTO

SET @NUMNOTAS = (SELECT COUNT(*) FROM [dbo].[NOTAS FISCAIS])

PRINT @NUMNOTAS

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT

SET @NUMERO_DIAS = 5
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()))

PRINT @DIA_SEMANA