DECLARE @NUMNOTAS INT

--SET @NUMNOTAS = (SELECT COUNT(*) FROM [dbo].[NOTAS FISCAIS])
SELECT @NUMNOTAS = COUNT(*) FROM [dbo].[NOTAS FISCAIS]

PRINT @NUMNOTAS

IF @NUMNOTAS > 70
	PRINT 'MUITA NOTA'
ELSE
	PRINT 'POUCA NOTA'